apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: core-api-19336
  namespace: MendPerformance
  annotations:
    github.com/project-slug: MendPerformance/core-api-19336
spec:
  type: service
  lifecycle: unknown
  owner: mend.io
